### ISSUE TITLE
CREATE: PROTECTED ROUTES, 404 PAGE 

### ISSUE THREAD

**Issue by IkboljonMe** [Yooupy/auction-app#14]
Later, implement protected route logic in frontend, once user is logged in or user's status is admin, give them proper rights. All logic should be implemented in Frontend.

[Protected route refs](https://gitlab.com/radcodeco/rad-workflows/-/blob/master/src/components/RouteGuard/index.tsx)

**Comment by IkboljonMe** [comment]
@botirjonshokirov That's awesome)

**Comment by botirjonshokirov** [comment]
thanks 😊
