### ISSUE TITLE
Get rid of deduplicated styles. Use global color variables for improving code readability!

### ISSUE THREAD

**Issue by IkboljonMe** [Yooupy/auction-app#25]
It'd be beginner friendly task, so let's close this issue quickly. We've used sass global files, you can check 'em in this [PR](https://github.com/Yooupy/auction-app/pull/24). Or you can visit style path [directly](https://github.com/Yooupy/auction-app/tree/main/client/src/styles).

**Comment by IkboljonMe** [comment]
@botirjonshokirov, @sherzod9sodikov , plz take a look.

**Comment by botirjonshokirov** [comment]
@IkboljonMe ✅
